gimulator-name: gimulator
gimulator-id: -1
gimulator-image: gimulator:latest
gimulator-type: master
gimulator-command: /app/result

gimulator-config-volume-name: gimulator-config-path
gimulator-config-volume-path: /config

gimulator-resource-requests-cpu: 200m
gimulator-resource-requests-memory: 500M
gimulator-resource-requests-ephemeral: 10M

gimulator-resource-limits-cpu: 400m
gimulator-resource-limits-memory: 1G
gimulator-resource-limits-ephemeral: 20M

logger-name: logger
logger-id: -2
logger-image: logger:latest
logger-type: finisher
logger-command: /app/logger
logger-role: logger

logger-resource-requests-cpu: 200m
logger-resource-requests-memory: 500M
logger-resource-requests-ephemeral: 10M

logger-resource-limits-cpu: 400m
logger-resource-limits-memory: 1G
logger-resource-limits-ephemeral: 20M

logger-s3-bucket: logger
logger-rabbit-uri: foo.com:5672
logger-rabbit-queue: logger
logger-record-dir: /tmp

shared-volume-name: shared-volume
shared-volume-path: /tmp/pod

namespace: default

default-resource-requests-cpu: 100m
default-resource-requests-memory: 100M
default-resource-requests-ephemeral: 10M

default-resource-limits-cpu: 200m
default-resource-limits-memory: 200M
default-resource-limits-ephemeral: 20M

env-var-key_logger-s3-url: LOGGER_S3_URL
env-var-key_logger-s3-access-key: LOGGER_S3_ACCESS_KEY
env-var-key_logger-s3-secret-key: LOGGER_S3_SECRET_KEY
env-var-key_logger-s3-bucket: LOGGER_S3_BUCKET
env-var-key_logger-recorder-dir: LOGGER_RECORDER_DIR
env-var-key_logger-rabbit-uri: LOGGER_RABBIT_URI
env-var-key_logger-rabbit-queue: LOGGER_RABBIT_QUEUE
env-var-key_client-id: CLIENT_ID
env-var-key_room-id: ROOM_ID
env-var-key_room-end-of-game: ROOM_END_OF_GAME_KEY
env-var-key_gimulator-host: GIMULATOR_HOST
env-var-key_gimulator-role-file-path: GIMULATOR_ROLES_FILE_PATH

env-var-val_logger-s3-bucket: xerac-logger
env-var-val_logger-recorder-dir: /var/log/logger
env-var-val_logger-rabbit-uri: ""
env-var-val_logger-rabbit-queue: ""
env-var-val_room-end-of-game: end-of-game
env-var-val_gimulator-host: localhost:3030
env-var-val_gimulator-roles-file-path: /etc/gimulator/config.yaml