gimulator-name: gimulator
gimulator-id: -1
gimulator-image: xerac/gimulator:staging
gimulator-type: master
gimulator-command: /app/gimulator
gimulator-config-volume-name: gimulator-config
gimulator-config-volume-path: /etc/gimulator
gimulator-requests-cpu: 200m
gimulator-requests-memory: 500M
gimulator-requests-ephemeral: 10M
gimulator-limits-cpu: 400m
gimulator-limits-memory: 1G
gimulator-limits-ephemeral: 20M
gimulator-host: localhost:3030
gimulator-roles-file-name: roles.yaml
gimulator-host-env-key: GIMULATOR_HOST
gimulator-role-file-path-env-key: GIMULATOR_ROLES_FILE_PATH

logger-name: logger
logger-id: -2
logger-image: xerac/logger:staging
logger-type: finisher
logger-command: /app/logger
logger-role: logger
logger-requests-cpu: 200m
logger-requests-memory: 500M
logger-requests-ephemeral: 10M
logger-limits-cpu: 400m
logger-limits-memory: 1G
logger-limits-ephemeral: 20M
logger-log-volume-name: logger-log
logger-log-volume-Path: /var/log/logger
logger-s3-bucket: xerac-logger
logger-recorder-dir: /var/log/logger
logger-s3-url-env-key: LOGGER_S3_URL
logger-s3-access-key-env-key: LOGGER_S3_ACCESS_KEY
logger-s3-secret-key-env-key: LOGGER_S3_SECRET_KEY
logger-s3-bucket-env-key: LOGGER_S3_BUCKET
logger-recorder-dir-env-key: LOGGER_RECORDER_DIR
logger-rabbit-uri-env-key: LOGGER_RABBIT_URI
logger-rabbit-queue-env-key: LOGGER_RABBIT_QUEUE

shared-volume-name: shared-volume
shared-volume-path: /tmp/pod

config-map-items-key: data

room-namespace: hub-system
room-end-of-game: end-of-game
room-id-env-key: ROOM_ID
room-end-of-game-env-key: ROOM_END_OF_GAME_KEY
client-id-env-key: CLIENT_ID

default-requests-cpu: 100m
default-requests-memory: 100M
default-requests-ephemeral: 10M
default-limits-cpu: 200m
default-limits-memory: 200M
default-limits-ephemeral: 20M