apiVersion: hub.xerac.cloud/v1
kind: Room
metadata:
  name: "room-123"
  namespace: "default"
spec:
  backoff-limit: 0
  active-dead-line-seconds: 10000
  id: 12
  sketch: "gimulator-roles"
  actors:
  - name: "agent-team"
    role: "agent"
    image: "xerac/paper-soccer-random-agent:staging"
    command: "/app/agent"
    type: "slave"
    id: 1
    resources:
      requests:
        cpu: "500m"
        memory: "1G"
        ephemeral: "30M"
      limits:
        cpu: "500m"
        memory: "1G"
        ephemeral: "30M"
  - name: "agent-team2"
    role: "agent"
    image: "xerac/paper-soccer-random-agent:staging"
    command: "/app/agent"
    type: "slave"
    id: 3
    resources:
      requests:
        cpu: "500m"
        memory: "1G"
        ephemeral: "30M"
      limits:
        cpu: "500m"
        memory: "1G"
        ephemeral: "30M"
  - name: "judge-team"
    role: "judge"
    image: "xerac/paper-soccer-judge:staging-1-ga14fb10"
    command: "/app/judge"
    type: "master"
    id: 2
    resources:
      requests:
        cpu: "500m"
        memory: "1G"
        ephemeral: "30M"
      limits:
        cpu: "500m"
        memory: "1G"
        ephemeral: "30M"
  config-maps:
  - name: "gimulator-roles"
    bucket: "xerac-roles"
    key: "roles.yaml"
