dataPVCName: "name-of-data-pvc"
gimulatorImage: "https://url/to/image"
outputVolumeSize: "1G" # or "500M"
resourceCPULimit: "1" # or "500m"
resourceMemoryLimit: "1G" # or "500M"
resourceEphemeralLimit: "1G" # or "500M"
