dataPVCNames: 
  public:
    - ""
    - ""
  private:
    - ""
    - ""

outputVolumeSize: "1G" # or "500M"

roles:
  "role-1": 
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
        ephemeral-storage: ""
      limits:
        memory: "128Mi"
        cpu: "500m"
        ephemeral-storage: ""
  "role-2": 
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
        ephemeral-storage: ""
      limits:
        memory: "128Mi"
        cpu: "500m"
        ephemeral-storage: ""

defaultResources:
  requests:
    memory: ""
    cpu: ""
    ephemeral-storage: ""
    storage: ""
  limits:
    memory: ""
    cpu: ""
    ephemeral-storage: ""
    storage: ""

gimulator:
  image: "xerac/gimulator:_"
  resources:
    requests:
      memory: ""
      cpu: ""
      ephemeral-storage: ""
      storage: ""
    limits:
      memory: ""
      cpu: ""
      ephemeral-storage: ""
      storage: ""