# permissions for end users to edit mls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ml-editor-role
rules:
- apiGroups:
  - hub.xerac.cloud
  resources:
  - mls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hub.xerac.cloud
  resources:
  - mls/status
  verbs:
  - get
