# permissions for end users to view mls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ml-viewer-role
rules:
- apiGroups:
  - hub.xerac.cloud
  resources:
  - mls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hub.xerac.cloud
  resources:
  - mls/status
  verbs:
  - get
