
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - hub.xerac.cloud
  resources:
  - rooms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hub.xerac.cloud
  resources:
  - rooms/status
  verbs:
  - get
  - patch
  - update
