# permissions for end users to view rooms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: room-viewer-role
rules:
- apiGroups:
  - hub.xerac.cloud
  resources:
  - rooms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hub.xerac.cloud
  resources:
  - rooms/status
  verbs:
  - get
